server:
  port: ${PORT}
spring:
  application:
    name: thekingmoss
  datasource:
    url: jdbc:mysql://localhost:3306/thekingmoss
    username: ${USER_NAME}
    password: ${PASSWORD_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${SECRET}
  expiration: 36000000

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

